import Head from "next/head";
import {
	Text,
	Center,
	Stack,
	Box,
	UnstyledButton,
	Group,
} from "@mantine/core";
import { useClipboard } from "@mantine/hooks";
import { Copy, Check } from "tabler-icons-react";
import StakingButton from "@/components/Atoms/StakingButton";

export default function Home() {
	const clipboard = useClipboard({ timeout: 500 });

	return (
		<>
			<Head>
				<title>CIEL Stake Pool</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Center h="80vh">
					<Stack>
						<Text
							fz={{ base: "8rem", lg: "14rem" }}
							fw="bold"
							ta="center"
							className={"fontNm"}
						>
							CIEL
						</Text>
						<Box
							style={{ overflowWrap: "break-word" }}
							className="nmOutline"
							sx={(theme) => ({
								margin: "auto",
								width: "100%",
								padding: "2rem",
								borderRadius: theme.radius.lg,
								[theme.fn.smallerThan("sm")]: {
									width: "20rem",
								},
							})}
						>
							<Text fz={{ base: "sm" }}>Ticker : CIEL</Text>
							<Group position="left" spacing="xs">
								<Text fz={{ base: "sm" }}>Pool ID :</Text>
								<UnstyledButton
									onClick={() =>
										clipboard.copy(
											"pool13qppafmw3vq5rl4ewmxv7zy84x3rshx9sdczs0zq40cxu0dqkrg"
										)
									}
								>
									{clipboard.copied ? (
										<Check size={"1rem"} />
									) : (
										<Copy size={"1rem"} />
									)}
								</UnstyledButton>
							</Group>
							<Text fz={{ base: "sm" }}>
								pool13qppafmw3vq5rl4ewmxv7zy84x3rshx9sdczs0zq40cxu0dqkrg
							</Text>
								<StakingButton />
						</Box>
					</Stack>
				</Center>
			</main>
		</>
	);
}
